-- 코드를 작성해주세요
WITH RECURSIVE TREE AS(
    SELECT ID,1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, T.GEN+1 AS GEN
    FROM ECOLI_DATA E JOIN TREE T ON E.PARENT_ID=T.ID
)
SELECT ID
FROM TREE
WHERE GEN=3
ORDER BY ID