-- 코드를 작성해주세요
SELECT T.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T ON I.ITEM_ID=T.ITEM_ID
WHERE I.ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID AS ITEM_ID
    FROM ITEM_TREE
    where parent_item_id is not null
)
ORDER BY ITEM_ID DESC