-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT O.ANIMAL_ID, O.NAME, O.DATETIME-I.DATETIME AS PERIOD
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
    ORDER BY PERIOD DESC
    FETCH FIRST 2 ROWS ONLY
)