-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT O.ANIMAL_ID, O.NAME, O.DATETIME-I.DATETIME AS DUR
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
    ORDER BY DUR DESC LIMIT 2
) A