-- 코드를 입력하세요
SELECT CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE*30*(1-0.01*DISCOUNT_RATE),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE=P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단','SUV') AND 
CAR_ID NOT IN
(
    SELECT C.CAR_ID
    FROM  CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID=H.CAR_ID
    WHERE START_DATE<='2022-11-30' AND END_DATE >='2022-11-01'
) 
    AND DURATION_TYPE='30일 이상' 
    AND DAILY_FEE*30*(1-0.01*DISCOUNT_RATE) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE, CAR_ID DESC