-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, 
ROUND( COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'),1) AS PUCHASTED_RATIO
FROM USER_INFO U  JOIN ONLINE_SALE O
ON U.USER_ID=O.USER_ID
WHERE JOINED LIKE '2021%' 
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR,MONTH