-- 코드를 작성해주세요
WITH RECURSIVE GENS AS(
    SELECT ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, G.GEN+1 AS GEN
    FROM ECOLI_DATA E JOIN GENS G ON E.PARENT_ID=G.ID
)
SELECT COUNT(*) AS COUNT, GEN AS GENERATION
FROM GENS G
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA C
    WHERE C.PARENT_ID=G.ID
)
GROUP BY GENERATION
ORDER BY GENERATION
