WITH RECURSIVE child AS (
    SELECT 
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT 
        e.ID,
        e.PARENT_ID,
        c.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA e
    JOIN child c
      ON e.PARENT_ID = c.ID
)

SELECT 
    COUNT(*) AS COUNT,
    c.GENERATION
FROM child c
LEFT JOIN ECOLI_DATA e
  ON c.ID = e.PARENT_ID
WHERE e.ID IS NULL
GROUP BY c.GENERATION
ORDER BY c.GENERATION;