-- 코드를 작성해주세요
WITH RECURSIVE GENERATION_CTE AS(
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT e.ID, gc.GENERATION+1
    FROM ECOLI_DATA e
    JOIN GENERATION_CTE gc ON e.PARENT_ID=gc.ID
)
SELECT COUNT(*) AS COUNT, GENERATION                    
FROM GENERATION_CTE
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;
