-- 코드를 입력하세요
SELECT F.PRODUCT_ID, PRODUCT_NAME,PRICE*SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT F JOIN FOOD_ORDER O ON F.PRODUCT_ID=O.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY F.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID