WITH TOTAL AS (
    SELECT
        H.HISTORY_ID,
        C.CAR_ID,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DUR,
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS DUR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT
    T.HISTORY_ID,
    ROUND(
        T.DAILY_FEE * T.DUR * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM TOTAL T
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON T.DUR_TYPE = P.DURATION_TYPE
    AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, T.HISTORY_ID DESC;