WITH INFO AS (
    SELECT
        H.HISTORY_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT
    I.HISTORY_ID,
    FLOOR(
        I.DAILY_FEE
        * I.DURATION
        * (100 - COALESCE(P.DISCOUNT_RATE, 0))
        / 100
    ) AS FEE
FROM INFO I
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON I.CAR_TYPE = P.CAR_TYPE
    AND P.DURATION_TYPE = CASE
        WHEN I.DURATION >= 90 THEN '90일 이상'
        WHEN I.DURATION >= 30 THEN '30일 이상'
        WHEN I.DURATION >= 7 THEN '7일 이상'
    END
ORDER BY FEE DESC, I.HISTORY_ID DESC;