-- 코드를 입력하세요
SELECT FLAVOR
FROM
(SELECT F.FLAVOR, SUM(J.TOTAL_ORDER)+SUM(F.TOTAL_ORDER) AS TOTAL
FROM FIRST_HALF F JOIN JULY J ON F.FLAVOR=J.FLAVOR
GROUP BY FLAVOR
ORDER BY TOTAL DESC) AS TOTALSUM
LIMIT 3