-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 AS HOUR
    FROM TIME
    WHERE HOUR<23
)
SELECT HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM TIME T LEFT JOIN ANIMAL_OUTS O ON T.HOUR=HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR