-- 코드를 입력하세요
WITH RECURSIVE HOURS AS(
    SELECT 0 AS HOUR
    UNION ALL
    
    SELECT HOUR+1 
    FROM HOURS 
    WHERE HOUR<23
)
SELECT J.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOURS J LEFT JOIN ANIMAL_OUTS A ON J.HOUR=HOUR(A.DATETIME)
GROUP BY J.HOUR
ORDER BY J.HOUR