WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR+1 AS HOUR
    FROM HOURS 
    WHERE HOUR<23   
)


SELECT H.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM HOURS H LEFT JOIN ANIMAL_OUTS O ON H.HOUR=HOUR(O.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR
