WITH MONEY AS (
    SELECT EMP_NO,
    CASE 
        WHEN AVG(SCORE)  >=96 THEN 'S'
        WHEN AVG(SCORE)>=90 THEN 'A'
        WHEN AVG(SCORE)  >=80 THEN 'B'
       ELSE 'C'
    END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT M.EMP_NO, EMP_NAME, GRADE, 
CASE 
    WHEN GRADE='S' THEN SAL*0.2
    WHEN GRADE='A' THEN SAL*0.15
    WHEN GRADE='B' THEN SAL*0.1
    ELSE 0 
END AS BONUS
FROM HR_EMPLOYEES E JOIN MONEY M ON E.EMP_NO=M.EMP_NO
ORDER BY M.EMP_NO