-- 코드를 작성해주세요
WITH AVG_GRADE AS (
    SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
    FROM HR_GRADE
    WHERE YEAR=2022
    GROUP BY EMP_NO
)
SELECT E.EMP_NO , EMP_NAME, 
    CASE
        WHEN A.AVG_SCORE>=96 THEN 'S'
        WHEN A.AVG_SCORE>=90 THEN 'A'
        WHEN A.AVG_SCORE>=80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN A.AVG_SCORE>=96 THEN SAL*0.2
        WHEN A.AVG_SCORE>=90 THEN SAL*0.15
        WHEN A.AVG_SCORE>=80 THEN SAL*0.1
        ELSE 0
    END AS BONUS

FROM AVG_GRADE A JOIN HR_EMPLOYEES E ON A.EMP_NO=E.EMP_NO
ORDER BY E.EMP_NO