-- 코드를 작성해주세요
SELECT C.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE C
JOIN ITEM_INFO P ON C.PARENT_ITEM_ID = P.ITEM_ID
JOIN ITEM_INFO I ON C.ITEM_ID =I.ITEM_ID
WHERE P.RARITY='RARE'
ORDER BY C.ITEM_ID DESC;