-- 코드를 작성해주세요
WITH MAX_ECOLI AS(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT M.YEAR AS YEAR, M.SIZE-E.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA E JOIN MAX_ECOLI M ON YEAR(E.DIFFERENTIATION_DATE)=M.YEAR
ORDER BY YEAR, YEAR_DEV