-- 코드를 입력하세요
SELECT DISTINCT R.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR R JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON R.CAR_ID=H.CAR_ID
WHERE CAR_TYPE='세단' AND
START_DATE LIKE ('%-10-%')
ORDER BY R.CAR_ID DESC