-- 코드를 작성해주세요
SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM (
    -- 2022년 점수합 구함
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR=2022
    GROUP BY EMP_NO
) G
JOIN HR_EMPLOYEES E ON G.EMP_NO=E.EMP_NO
-- 최대점수 구해야함
WHERE G.SCORE=(
    SELECT MAX(TOTAL)
    FROM (
        SELECT EMP_NO, SUM(SCORE) AS TOTAL
        FROM HR_GRADE
        WHERE YEAR=2022
        GROUP BY EMP_NO
    ) T
)